### PR TITLE
Enhance fasterid with key mapping and database storage

### PR DESCRIPTION
**Pull request by mielvds**
Hi! I was experimenting with fasterid to see whether it could fit the URI uses cases we have here at our organisation. As a result, I developed some features that are probably up for debate. Hence, this PR!

**Use cases**

Aside from generating nice and reproducible identifiers (which erdi8 solves; thanks for that!), we need the following features:
1. mapping a key to an identifier: in many cases, we need to reproduce the same URI for the same hash because we don't keep state between ETL runs.
2. production-grade backup: it's extremely important that we don't "loose" the minted identifiers (ie. to avoid clashes and so on), so they need to be properly backed up using reliable processes that we know.

**What does this PR do?**

In order to serve the use case above, this PR includes the following:

- A switch from simple file storage to SQLAlchemy to allow database backup, but also the new features below. The default is sqllite, but this also allows postgreSQL, which is what we will use. You can set SQLALCHEMY_DATABASE_URL, but if not there, it will use FASTERID_FILENAME as a sort of "backwards-compatibility".
- An extension of the Web API to also allow an array of keys, which, if unknown, will be mapped to IDs and stored in the database. For every key provided, it will always return the same ID.
- Every prefix now has it's own ID generation scheme with the possiblity for having no prefix at all, like before. The last issued identifier is now stored in the database together with the prefix. Hence, you can have the same ID twice as long as the prefix is different. This is a breaking change which I'm not sure about. Happy to hear your thoughts!
- A small refactor in multiple files as a result of the SQLAlchemy integration.
- Some code formatting using black and isort.

### CODE REVIEW

**Comment by athalhammer** [comment]
Thanks for the pull request @mielvds! This is great!

I think this could be a quick merge but we need some minor adaptations:

1. Introduce consistently the concept of an optional mapping key
2. Abstract "database log" (optional) as an alternative to "file log" (default)

**Comment by mielvds** [comment]
I agree! I'll work towards those changes

**Comment by mielvds** [comment]
@athalhammer could you elaborate on how you see your two points implemented?

Regarding 1. : I'm not sure I follow. If no key is supplied, there's no mention in the response?
Regarding 2.: How would mapped IDs and prefixes be stored in the default file log?

**Comment by mielvds** [comment]
@athalhammer I added two things:
- if you (don't) supply a `key:[]` in the request, you (don't) get a `map:{}` in the response
- I brought back the simple file logging which is the default. You can switch to database by setting `USE_DATABASE=True`. 

The latter is implemented in a different branch (see https://github.com/viaacode/fasterid/pull/1) that also adds
- splitting the code in different files for better maintenance
- upgrade `fastapi` to 0.101.0 and `pydantic` to version 2 which does results in some minor changes in how settings are handled. I updated the readme accordingly.
- upgrade to python 3.11
- unittests

I would prefect merging the pydantic 2 branch into this one first before continuing the discussion...So if you have any objections, please let me know.

**Comment by athalhammer** [comment]
Regarding 1:  yes, that's what I meant - if you don't provide a key the output also does not include the `map`

**Comment by athalhammer** [comment]
Somehow it doesn't add up: most of the requests of the `README.md` file don't work any longer as expected. E.g. with a full clone of the repo and no amendments I get

```
curl -X POST http://127.0.0.1:8000 --data '{"number": 4, "prefix": "https://example.com/", key: ["test"]}' -H "content-type: application/json" | jq
{"id":["sgyy435zqc"]}
```

**Comment by mielvds** [comment]
I noticed strange behaviour too during unittesting with the `Annotated` typing of the request parameter.Somehow the body doesn't get passed any longer... Could you try removing the Annotated stuf and simply put `request: RequestModel | None`?

**Comment by athalhammer** [comment]
That seems to work - What's the `Annotated` breaking?

**Comment by mielvds** [comment]
Not sure... It fails silently; parameters are simply not passed. I'm also just a python beginner, so this pydantic/fastapi is quite complicated

**Comment by athalhammer** [comment]
Opened PR https://github.com/viaacode/fasterid/pull/2

**Comment by athalhammer** [comment]
@mielvds I'm still unclear about the `key` parameter. In case I do a post with the same key, it should return the mapped identifier that was previously assigned for that key, right?

So then a repeated call should not provide different identifier, right?
```
$ curl -X POST http://127.0.0.1:15433 --data '{"number": 3, "prefix": "https://example.com/", "key": ["asdf"]}' -H "content-type: application/json" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   219  100   155  100    64  38856  16044 --:--:-- --:--:-- --:--:-- 73000
{
  "id": [
    "https://example.com/n7yc4gdt84",
    "https://example.com/rtyb9t95b5",
    "https://example.com/wfy9h65gd6"
  ],
  "map": {
    "asdf": "https://example.com/b2y8phzsg7"
  }
}
$ curl -X POST http://127.0.0.1:15433 --data '{"number": 3, "prefix": "https://example.com/", "key": ["asdf"]}' -H "content-type: application/json" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   219  100   155  100    64  46241  19093 --:--:-- --:--:-- --:--:-- 73000
{
  "id": [
    "https://example.com/fny7vvw4j8",
    "https://example.com/k8y737rfm9",
    "https://example.com/pvy68kmrpb"
  ],
  "map": {
    "asdf": "https://example.com/tgy5fxh3rc"
  }
}

```

**Comment by athalhammer** [comment]
I'm thinking about supporting the map and id functions as separate endpoints as a logfile-based mapping may not have the the required retrieval performance. Would the following workflow make sense:

1. Client creates identifier via `/id` endpoint
2. Client uses returned identifier and calls `/map` to store the key-value pair

Let me reflect on the implications of either bundling the whole creation+map step in a single operation (less http traffic) or separating it - to the extent that you could think about having a separate microservice that takes care of the map storage

**Comment by mielvds** [comment]
> @mielvds I'm still unclear about the `key` parameter. In case I do a post with the same key, it should return the mapped identifier that was previously assigned for that key, right?
> 
> So then a repeated call should not provide different identifier, right?
> 
> ```
> $ curl -X POST http://127.0.0.1:15433 --data '{"number": 3, "prefix": "https://example.com/", "key": ["asdf"]}' -H "content-type: application/json" | jq
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   219  100   155  100    64  38856  16044 --:--:-- --:--:-- --:--:-- 73000
> {
>   "id": [
>     "https://example.com/n7yc4gdt84",
>     "https://example.com/rtyb9t95b5",
>     "https://example.com/wfy9h65gd6"
>   ],
>   "map": {
>     "asdf": "https://example.com/b2y8phzsg7"
>   }
> }
> $ curl -X POST http://127.0.0.1:15433 --data '{"number": 3, "prefix": "https://example.com/", "key": ["asdf"]}' -H "content-type: application/json" | jq
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   219  100   155  100    64  46241  19093 --:--:-- --:--:-- --:--:-- 73000
> {
>   "id": [
>     "https://example.com/fny7vvw4j8",
>     "https://example.com/k8y737rfm9",
>     "https://example.com/pvy68kmrpb"
>   ],
>   "map": {
>     "asdf": "https://example.com/tgy5fxh3rc"
>   }
> }
> ```

It shouldn't, no, but with the simple file storage...I'm not sure how to persist the mappings, so it currently returns new ones. 


> I'm thinking about supporting the map and id functions as separate endpoints as a logfile-based mapping may not have the the required retrieval performance. Would the following workflow make sense:
> 
>     1. Client creates identifier via `/id` endpoint
> 
>     2. Client uses returned identifier and calls `/map` to store the key-value pair
> 

Problem is that the client doesn't know whether an ID was already stored or not, so it doesn't know when to call `/map` Unless it starts keeping state, but then things become complicated and inefficient.  I'd beware of involving the client too much.

What I could imagine though, is a GET `/map/<key>` where the API just returns the correct ID, regardless of whether it was already created or not. This would be more RESTful even. Downside: you loose the ability to map multiple keys in one request, but that's probably no issue.

> 
> Let me reflect on the implications of either bundling the whole creation+map step in a single operation (less http traffic) or separating it - to the extent that you could think about having a separate microservice that takes care of the map storage

Yes, separation could be good

**Comment by athalhammer** [comment]
Thanks again for this PR, @mielvds ! I was thinking for quite some while about it, tried the additional functionality, and came to the conclusion that a mapping service should be a separate entity. Such service could call the fasterid service if it needs a new id (the provided key has no mapping) or the client could take care of this themselves. Baking it into fasterid creates some additional overhead. I see some very good elements in your PR and I will take it for inspiration for maturing fasterid. Thanks again!

**Pull request closed without merging**
